language: php
install:
  - composer install
script:
  - mkdir -p build/logs
  - phpunit --testsuite unit --coverage-clover build/logs/clover.xml
php:
  - '7.0'
after_success:
  - travis_retry php vendor/bin/coveralls
