<?php

namespace ChingShop\Modules\Sales\Providers;

use App;
use ChingShop\Modules\Sales\Model\Basket\Basket;
use ChingShop\Modules\Sales\Model\Clerk;
use Illuminate\Contracts\Auth\Guard;
use Illuminate\Foundation\Application;
use Illuminate\Session\Store;
use Illuminate\Support\ServiceProvider;
use Lang;
use View;

/**
 * Class SalesServiceProvider.
 */
class SalesServiceProvider extends ServiceProvider
{
    /**
     * Additional Compiled Module Classes.
     *
     * Here you may specify additional classes to include in the compiled file
     * generated by the `artisan optimize` command. These should be classes
     * that are included on basically every request into the application.
     *
     * @return array
     */
    public static function compiles()
    {
        return [];
    }

    /**
     * Register the Sales module service provider.
     *
     * This service provider is a convenient place to register your modules
     * services in the IoC container. If you wish, you may make additional
     * methods or service providers to keep the code more focused and granular.
     *
     * @return void
     */
    public function register()
    {
        App::register('ChingShop\Modules\Sales\Providers\RouteServiceProvider');

        /* @noinspection RealpathOnRelativePathsInspection */
        View::addNamespace('sales', realpath(__DIR__.'/../Resources/Views'));

        $this->app->singleton(
            Clerk::class,
            function () {
                return new Clerk(
                    $this->app->make(Store::class),
                    $this->app->make(Guard::class),
                    $this->app->make(Basket::class)
                );
            }
        );
    }

    /**
     * Bootstrap the application events.
     *
     * Here you may register any additional middleware provided with your
     * module with the following addMiddleware() method. You may pass in
     * either an array or a string.
     *
     * @return void
     */
    public function boot()
    {
    }
}
